version: '3.8'

services:
  api:
    build:
      context: ./nancy-services
    ports:
      - "8000:8000"
    depends_on:
      - chromadb
      - neo4j
      - ollama
    env_file:
      - .env
    environment:
      - CHROMA_HOST=chromadb
      - NEO4J_URI=bolt://neo4j:7687
      - OLLAMA_HOST=http://ollama:11434
      - NANCY_MIGRATION_MODE=mcp
    volumes:
      - ./data:/app/data                    # Persistent Nancy data
      - ./project_docs:/app/project_docs    # Directory for project documents
      - ./benchmark_data:/app/benchmark_data # Benchmark test data
      - ./nancy-config.yaml:/app/nancy-config.yaml # Nancy configuration
      - ./mcp-servers:/app/mcp-servers      # MCP servers directory

  baseline-rag:
    build:
      context: ./baseline-rag
    ports:
      - "8002:8002"
    depends_on:
      - chromadb
      - ollama
    env_file:
      - .env
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - OLLAMA_HOST=ollama:11434
    volumes:
      - ./benchmark_data:/app/benchmark_data

  chromadb:
    image: chromadb/chroma
    ports:
      - "8001:8000" # Exposing ChromaDB's API on port 8001 to avoid conflict with our api service
    volumes:
      - chromadb_data:/chroma/.chroma

  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 3.5G
    # Uncomment for GPU support:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  chromadb_data:
  neo4j_data:
  neo4j_logs:
  ollama_data:
